/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 brouche.gltf 
Author: 𝔼ℕ𝔼𝔸 𝕃𝔼 𝔽𝕆ℕ𝕊 (https://sketchfab.com/enealefons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/uxr-circle-rotating-ring-e1ec7c0ea9314a689feecba3ca4c8240
Title: UXR circle rotating ring
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/models/brouche.gltf");
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Sketchfab_Scene">
				<group
					name="Sketchfab_model"
					position={[-99.266, 0, 99.218]}
					rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
					<group name="CIRCLEringfbx" rotation={[Math.PI / 2, 0, 0]}>
						<group name="Object_2">
							<group name="RootNode">
								<group
									name="torus"
									position={[-0.017, 0.526, 99.238]}
									rotation={[0, 0, Math.PI / 2]}
									scale={[30.641, 29.486, 30.641]}>
									<mesh
										name="torus_WorldGridMaterial_0"
										geometry={nodes.torus_WorldGridMaterial_0.geometry}
										material={materials.WorldGridMaterial}
									/>
									<mesh
										name="torus_Material2_0"
										geometry={nodes.torus_Material2_0.geometry}
										material={materials.Material2}
									/>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/brouche.gltf");
