name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: |
          cd my-portfolio
          npm install

      - name: Build project
        run: cd my-portfolio && CI=false npm run build

      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: deploy
          path: deploy

      - name: Remove existing deploy artifacts
        run: rm -rf deploy/*

      - name: Copy build artifacts to deploy branch
        run: cp -R my-portfolio/dist/* deploy/

      - name: Commit and push changes
        run: |
          cd deploy
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "Auto-generated build from main branch"
          git push origin deploy
